language: node_js
node_js:
  - '4'
script:
  - npm install
  - npm test
deploy:
  provider: npm
  email: demsking@gmail.com
  api_key:
    secure: ycQzQuzDNQshlZcqz2gyb+VMUUrkJDSWZxJJxhwKWNT2pAigMl7IKuYD/JEzrbRj0Ijm/K2OTQhpy1ESqf4rXtXhbb1gFlMJkhHZDYnBRfY+EQXv4NbMnDArb9+YQEIeroQrqdSK+EzKyW49Nk9tU+5DCCzMDqyJNgKH74cVOInFy5gcBLOqxt7ic6vCqBsQleBhE5+9ZafbPoPH0YFG679FLWIudBeZYBRDYqyebpeX9fpyBqHUa5ed5J367QKJnY96EdMlFHoWVw2afqajMq/0xVSVCQknSa/qRn9zgAUe5RgIdUqAXigikWwyGlH57XKq11wosN1i3XApEITT6VMBGrKrUgwtzp6677EaTDzUUKGyFvQoE9FlagUq2k1BP5Jhc3Z1NgrtczJnanzRCy5IKzWyjnj25ZaOAjchMbLOebLDSr+/tuQAnERbfK+Q9Lb1JX4UPY55A1a1XEFnGu5GgZ8qE6ArYJUh5f5nqs3DkkfDQf/GWjbSpufiUIxK6OSOcdoqZ+i5yUTT9Z7uWcQvUdQuZSY4BXyT50bn90KHUZrKqHNF30hlxb9cPKjhwywxUcmmJqBlyq6Futz3ypmVTGCIS2J/JpeaoCBLrXVntljDFvLd/af0CSz1ayrrNJ2ksu2/gy+gYxUu3F95oW3ihWpFVELbaYJalmliPhY=
  on:
    tags: false
    repo: demsking/vue-components-form
