language: node_js
node_js:
- '8'
script:
- npm install
- npm run coveralls
deploy:
  provider: npm
  email: demsking@gmail.com
  api_key:
    secure: hzdYCbqaZf8CYmKBbv707wgQSpAuU54fqzrHBsffOxi12JROINllvHRAp06mngB5LfIerhXxBmuTLZ/FInfVB1wpi8M1AOtpUg6zj1ETBtFSTBQBoXyaL2OzPPCAKWeKyxnWSHHaakIxiJr26Ug+J0fQsb44KcRA8f2dceyTxxi6dkw6DDs6UcckAxrmsvppmAHr9eld2PpCB7zjPOpXfPAZ7S6QnwGFKqBUVw68LGp7bC/qKA5r1Sj38wP3KIgej8N38fQr+h38dD7NLX/DXGIJgsUX80qVxY9dv0WGeVIyrJj04a39EPgeAePj3R47Q6Dpjd9RzF5tTrWQ0Pr8XhrAKBAWtoXh7gOHNNAcMKQ0jrIg3Fx6+wQAXi9ihQIpObVvXI7Rla6ZJR3SlBzoVW0jPy/umsBQKAXFqOR291rvUHXBN7GpHHRFcuxDoySKcOYM9oRp/GcCvOC4/zAYxJD+7VXRA/NWJuH1KJrxps/zBoKWzR4O7K3ro1t6wjFHnu1zFoOKvbjQUExkmRWWlnd4YbF/F4tC4tuEiccqQtiEGiWjwlB96G06wxL8wOkTICNctIIo753+zllRKXZCy3Imfd07YzEV1Q0v1KMmN3EYEEfAEjoTVge41V+Qgm/J8jM9HzrHmI/4m2JcPbiQEbLEVq/y+9kCaChb54S1ebI=
  on:
    branch: master
    tags: true
    repo: vue-json-schema/form-schema
